// Host app generated by tools/play_ai_pack/make_ai_pack.py for {{REPO}}.
//
// Flow: Play AI Delivery hands us the pack directory -> we read the
// litertlm_pack.json sidecar the generator put in the device group we received
// (file name, sha256, backend, session defaults) -> LiteRT-LM loads that file
// on that backend -> one prompt, timed. Everything shown on screen is what a
// tester needs to report back: device/SoC/RAM, group, file, sha256, tok/s.
package {{APPLICATION_ID}}

import android.app.ActivityManager
import android.app.Activity
import android.os.Build
import android.os.Bundle
import android.widget.Button
import android.widget.TextView
import androidx.activity.ComponentActivity
import androidx.activity.result.IntentSenderRequest
import androidx.activity.result.contract.ActivityResultContracts
import androidx.lifecycle.lifecycleScope
import com.google.ai.edge.litertlm.Backend
import com.google.ai.edge.litertlm.Engine
import com.google.ai.edge.litertlm.EngineConfig
import com.google.ai.edge.litertlm.Message
import com.google.android.play.core.aipacks.AiPackManager
import com.google.android.play.core.aipacks.AiPackManagerFactory
import com.google.android.play.core.aipacks.AiPackState
import com.google.android.play.core.aipacks.AiPackStateUpdateListener
import com.google.android.play.core.aipacks.model.AiPackStatus
import com.google.android.play.core.aipacks.model.AiPackStorageMethod
import java.io.File
import java.security.MessageDigest
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.launch
import kotlinx.coroutines.withContext
import org.json.JSONObject

class MainActivity : ComponentActivity() {
  private val packName = "{{PACK_NAME}}"
  private lateinit var manager: AiPackManager
  private lateinit var logView: TextView
  private var confirmationShown = false

  private val confirmationLauncher =
    registerForActivityResult(ActivityResultContracts.StartIntentSenderForResult()) { result ->
      log(if (result.resultCode == Activity.RESULT_OK) "download confirmed" else "download declined")
    }

  private val listener = AiPackStateUpdateListener { state -> onState(state) }

  override fun onCreate(savedInstanceState: Bundle?) {
    super.onCreate(savedInstanceState)
    setContentView(R.layout.activity_main)
    logView = findViewById(R.id.log)
    findViewById<TextView>(R.id.device).text = deviceLine()
    manager = AiPackManagerFactory.getInstance(this)
    findViewById<Button>(R.id.run).setOnClickListener { start() }
    // `adb shell am start -n <id>/.MainActivity --ez autorun true` drives the whole flow unattended.
    if (intent.getBooleanExtra("autorun", false)) start()
  }

  override fun onResume() {
    super.onResume()
    manager.registerListener(listener)
  }

  override fun onPause() {
    manager.unregisterListener(listener)
    super.onPause()
  }

  private fun deviceLine(): String {
    val am = getSystemService(ACTIVITY_SERVICE) as ActivityManager
    val mi = ActivityManager.MemoryInfo().also { am.getMemoryInfo(it) }
    val soc = if (Build.VERSION.SDK_INT >= 31) "${Build.SOC_MANUFACTURER} ${Build.SOC_MODEL}" else "n/a (<31)"
    return "${Build.BRAND}/${Build.DEVICE} (${Build.MODEL})  SoC ${soc}  RAM ${mi.totalMem / 1_000_000} MB  " +
      "Android ${Build.VERSION.RELEASE}"
  }

  private fun start() {
    // Never trust a cached location: the pack may be gone after an update or a data clear.
    val location = manager.getPackLocation(packName)
    if (location != null) {
      log("pack present (storage ${storageName(location.packStorageMethod())})")
      runModel(location.assetsPath())
      return
    }
    log("pack not present; fetch($packName)")
    manager.fetch(listOf(packName)).addOnCompleteListener { task ->
      if (!task.isSuccessful) log("fetch failed: ${task.exception}")
      else task.result.packStates()[packName]?.let { onState(it) }
    }
  }

  private fun onState(state: AiPackState) {
    when (state.status()) {
      AiPackStatus.PENDING -> log("pending")
      AiPackStatus.DOWNLOADING ->
        log("downloading ${state.bytesDownloaded() / 1_000_000} / ${state.totalBytesToDownload() / 1_000_000} MB")
      // transferProgressPercentage() reported 10000 at completion on a Galaxy S26 (ai-delivery 0.2.0-beta01); logged raw.
      AiPackStatus.TRANSFERRING -> log("transferring, transferProgressPercentage()=${state.transferProgressPercentage()}")
      AiPackStatus.COMPLETED -> {
        log("completed")
        manager.getPackLocation(packName)?.let { runModel(it.assetsPath()) } ?: log("completed but no location")
      }
      AiPackStatus.FAILED -> log("failed, error code ${state.errorCode()}")
      AiPackStatus.CANCELED -> log("canceled")
      AiPackStatus.WAITING_FOR_WIFI, AiPackStatus.REQUIRES_USER_CONFIRMATION -> {
        if (!confirmationShown) {
          confirmationShown = true
          manager.showConfirmationDialog(confirmationLauncher)
        }
      }
      AiPackStatus.NOT_INSTALLED -> log("not installed")
      else -> log("status ${state.status()}")
    }
  }

  private fun storageName(m: Int) =
    when (m) { AiPackStorageMethod.STORAGE_FILES -> "files"; AiPackStorageMethod.APK_ASSETS -> "apk-assets"; else -> "$m" }

  private fun runModel(assetsPath: String?) {
    if (assetsPath == null) { log("no assets path"); return }
    val modelDir = File(assetsPath, "model")
    val sidecar = File(modelDir, "litertlm_pack.json")
    if (!sidecar.exists()) {
      // Only the un-suffixed index reached this device: it matched no device group.
      val index = File(assetsPath, "index/litertlm_pack_index.json")
      log(if (index.exists()) "no model for this device group; index:\n${index.readText()}"
          else "pack has no sidecar and no index at $modelDir")
      return
    }
    val meta = JSONObject(sidecar.readText())
    val file = File(modelDir, meta.getString("file"))
    val backendName = meta.getString("backend")
    log("group ${meta.optString("group")}  file ${file.name}  ${file.length() / 1_000_000} MB  backend $backendName")
    lifecycleScope.launch(Dispatchers.IO) {
      val digest = sha256(file)
      val expected = meta.optString("sha256")
      log("sha256 ${if (digest == expected) "OK" else "MISMATCH expected $expected got"} $digest")
      val backend: Backend = when (backendName) {
        "gpu" -> Backend.GPU()
        "npu" -> Backend.NPU(applicationInfo.nativeLibraryDir)
        else -> Backend.CPU()
      }
      val t0 = System.nanoTime()
      try {
        Engine(EngineConfig(modelPath = file.absolutePath, backend = backend, cacheDir = cacheDir.absolutePath)).use { engine ->
          engine.initialize()
          val loadS = (System.nanoTime() - t0) / 1e9
          log("engine ready in %.1f s".format(loadS))
          engine.createConversation().use { conversation ->
            val t1 = System.nanoTime()
            val reply = conversation.sendMessage(Message.user("{{PROMPT}}"))
            val genS = (System.nanoTime() - t1) / 1e9
            val text = reply.toString()
            log("reply (%.1f s, %d chars):\n%s".format(genS, text.length, text))
          }
        }
      } catch (e: Throwable) {
        log("engine error: $e")
      }
    }
  }

  private fun sha256(f: File): String {
    val md = MessageDigest.getInstance("SHA-256")
    f.inputStream().use { s ->
      val buf = ByteArray(1 shl 20)
      while (true) { val n = s.read(buf); if (n < 0) break; md.update(buf, 0, n) }
    }
    return md.digest().joinToString("") { "%02x".format(it) }
  }

  private fun log(line: String) {
    lifecycleScope.launch(Dispatchers.Main) { logView.append(line + "\n") }
    android.util.Log.i("AiPackTest", line)
  }
}
