#!/bin/bash
# Round 10: a copy of round 5's scripts/s26_keeper.sh (unchanged logic below its header), so that the NPU chain's keeper
# never reads a file another round may replace while it runs. Started by scripts/s26_npu_chain.sh.
# Round 5: the S26 hold keeper of the d1-omni LiteRT lane = d1_3b_work's scripts/d1_s26_keeper.sh (round 4): the named
# waiting line (community_accel_work/queue_cli.py) and an owned hold. Started by the chain (one keeper per hold).
#   usage: s26_keeper.sh <signal dir> <hold file> <script name>
# 1. `queue_cli.py wait <hold file> <script name> <this shell's pid>`: in the line behind the entries whose keepers are
#    waiting, acquires the owned hold (device_hold.py) with THIS shell's pid when the hold is free; never forces, never
#    clears another session's hold (a dead holder's stale hold is cleared by device_hold.acquire itself);
# 2. writes <signal dir>/HOLD_ACQUIRED ("<serial>", "pid <pid> since <time>");
# 3. keeps the hold until <signal dir>/RELEASE_HOLD appears or HOLD_LIMIT seconds (default 1,800 = the 30-minute window)
#    after acquiring, then `hold_cli.py release <hold file> <pid>` (removes the hold only when it is this pid's) and writes
#    <signal dir>/HOLD_RELEASED. Gives up waiting after WAIT_LIMIT seconds (default 4 h; queue_cli exit 3 -> GAVE_UP).
# Do not edit this file while a keeper runs (bash reads a script as it goes): write a new file and `mv` it over this one.
set -u
SIG=${1:?signal dir}; LOCK=${2:?hold file}; NAME=${3:?script name}
CA=${CA:?set CA to the directory of the shared-device hold tools (queue_cli.py, hold_cli.py)}
SERIAL=${D1_SERIAL:-RFGL80R6A6H}
HOLD_LIMIT=${HOLD_LIMIT:-1800}
WAIT_LIMIT=${WAIT_LIMIT:-14400}
mkdir -p "$SIG"; rm -f "$SIG/HOLD_ACQUIRED" "$SIG/RELEASE_HOLD" "$SIG/HOLD_RELEASED" "$SIG/GAVE_UP"
echo "keeper pid $$ started $(date '+%F %T') hold=$LOCK name=$NAME hold_limit=${HOLD_LIMIT}s wait_limit=${WAIT_LIMIT}s"
echo "line at start:"; python3 "$CA/queue_cli.py" list "$LOCK" | sed 's/^/  /'
if ! python3 "$CA/queue_cli.py" wait "$LOCK" "$NAME" $$ --timeout "$WAIT_LIMIT" --poll 2; then
  echo "gave up waiting $(date '+%F %T')"; date '+%F %T' > "$SIG/GAVE_UP"; exit 3
fi
ACQ=$(date +%s)
END=$(( ACQ + HOLD_LIMIT ))
{ echo "$SERIAL"; echo "pid $$ since $(date -r "$ACQ" '+%Y-%m-%d %H:%M:%S')"; } > "$SIG/HOLD_ACQUIRED"
echo "HOLD ACQUIRED by pid $$ at $(date -r "$ACQ" '+%F %T'); hold file: $(cat "$LOCK")"
echo "auto release at $(date -r $END '+%T')"
while [ ! -f "$SIG/RELEASE_HOLD" ]; do
  if [ "$(date +%s)" -ge "$END" ]; then echo "hold limit reached $(date '+%F %T')"; break; fi
  sleep 2
done
python3 "$CA/hold_cli.py" release "$LOCK" $$
rm -f "$SIG/HOLD_ACQUIRED"
date '+%F %T' > "$SIG/HOLD_RELEASED"
echo "HOLD RELEASED at $(date '+%F %T'); hold file now: $(cat "$LOCK" 2>/dev/null || echo '<absent>')"
