"""Faithful eager validation of the DEPLOYED Ovis2.5-2B fast_vlm path: fixed 512x512
squash (like the runtime), our static vision Encoder+Adapter -> 256 image embeddings,
spliced (NO learned indicators, matching the 256-token bundle) into a ChatML prompt,
generated by model.llm. If this describes a real photo coherently, the bundle's
vision path + prompt contract is sound (the on-device .litertlm test is device-only).

    ~/clipconv/bin/python ovis_work/eager_validate_ovis.py [image] [question]
"""
import sys, numpy as np, torch
import transformers.modeling_utils as _mu
if not hasattr(_mu.PreTrainedModel, "all_tied_weights_keys"): _mu.PreTrainedModel.all_tied_weights_keys = {}
if not hasattr(_mu.PreTrainedModel, "is_parallelizable"): _mu.PreTrainedModel.is_parallelizable = False
from transformers import AutoModelForCausalLM
from PIL import Image

sys.path.insert(0, "ovis_work")
import ovis_static

MID = "AIDC-AI/Ovis2.5-2B"
IMG = sys.argv[1] if len(sys.argv) > 1 else "colorization_work/repo/imgs/ansel_adams.jpg"
Q = sys.argv[2] if len(sys.argv) > 2 else "Describe this image in detail."
GH = GW = 32; HS = 2; N_PATCH = GH * GW; N_TOK = N_PATCH // (HS * HS); N_IND = 4


def load():
  return AutoModelForCausalLM.from_pretrained(
      MID, trust_remote_code=True, torch_dtype=torch.float32, low_cpu_mem_usage=True).eval()


print("loading Ovis2.5-2B...")
try:
  model = load()
except TypeError as e:
  if "tie_weights" not in str(e): raise
  for name, mod in list(sys.modules.items()):
    if "modeling_ovis2_5" in name and hasattr(mod, "Ovis2_5"):
      cls = mod.Ovis2_5; _o = cls.tie_weights; cls.tie_weights = lambda self, *a, **k: _o(self)
  model = load()

# --- build the same static Encoder + Adapter the converter ships (deployed path) ---
vt = model.visual_tokenizer
vm = vt.vit.vision_model
emb = vm.embeddings
ovis_static.install_static_vision(model, GH, GW)
enc = vm.encoder
apply_rope = next(m.apply_rotary_pos_emb_vision for n, m in sys.modules.items()
                  if "modeling_ovis2_5" in n and hasattr(m, "apply_rotary_pos_emb_vision"))


def _attn(self, hidden_states, cu_seqlens=None, position_embeddings=None):
  L, _ = hidden_states.shape
  q = self.q_proj(hidden_states).view(L, self.num_heads, self.head_dim)
  k = self.k_proj(hidden_states).view(L, self.num_heads, self.head_dim)
  v = self.v_proj(hidden_states).view(L, self.num_heads, self.head_dim)
  if self.use_rope:
    cos, sin = position_embeddings
    q, k = apply_rope(q.unsqueeze(0), k.unsqueeze(0), cos, sin); q, k = q.squeeze(0), k.squeeze(0)
  q, k, v = q.transpose(0, 1), k.transpose(0, 1), v.transpose(0, 1)
  attn = ((q * self.scale) @ k.transpose(-2, -1)).softmax(dim=-1)
  return self.out_proj((attn @ v).transpose(0, 1).reshape(L, self.embed_dim))


for layer in enc.layers:
  layer.self_attn.forward = _attn.__get__(layer.self_attn, type(layer.self_attn))

perm = torch.tensor([(hb * HS + hi) * GW + (wb * HS + wj)
                     for hb in range(GH // HS) for wb in range(GW // HS)
                     for hi in range(HS) for wj in range(HS)], dtype=torch.long)
grid = torch.tensor([[1, GH, GW]], dtype=torch.long)


def encode(img01):  # [1,512,512,3] [0,1] -> [256,4608]
  x = ((img01 - 0.5) / 0.5).permute(0, 3, 1, 2)
  p = emb.patch_embedding(x).flatten(2).transpose(1, 2).reshape(N_PATCH, -1)
  p = p.index_select(0, perm) + emb._pe_const
  h, states = enc(p, grid, output_hidden_states=True)
  return states[-1].reshape(N_TOK, -1)


def adapt(feat):  # [256,4608] -> [256,2048]
  logits = vt.head(feat)
  tokens = torch.softmax(logits, dim=-1, dtype=torch.float32).to(logits.dtype)
  tokens = torch.cat((tokens, torch.zeros(tokens.shape[0], N_IND, dtype=tokens.dtype)), dim=1)
  return model.vte(tokens)


tok = model.text_tokenizer
wte = model.llm.get_input_embeddings()
pil = Image.open(IMG).convert("RGB").resize((512, 512), Image.BILINEAR)
img01 = (torch.from_numpy(np.asarray(pil)).float() / 255.0).unsqueeze(0)

with torch.no_grad():
  img_emb = adapt(encode(img01))  # [256,2048]
  pre_ids = tok("<|im_start|>user\n", add_special_tokens=False, return_tensors="pt").input_ids
  post_ids = tok("\n" + Q + "<|im_end|>\n<|im_start|>assistant\n",
                 add_special_tokens=False, return_tensors="pt").input_ids
  seq = torch.cat([wte(pre_ids)[0], img_emb, wte(post_ids)[0]], dim=0).unsqueeze(0)
  out = model.llm.generate(inputs_embeds=seq, max_new_tokens=160, do_sample=False,
                           pad_token_id=tok.pad_token_id or tok.eos_token_id)
resp = tok.decode(out[0], skip_special_tokens=True)
print("\n=== QUESTION ===\n" + Q)
print("\n=== RESPONSE (deployed path: static-512 vision, 256 tokens, no indicators) ===\n" + resp)
